In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.read_csv("/content/drive/MyDrive/빅예분3조/Data/prescale/KPU_DATA_MERGE1.csv", encoding='euc-kr')
df2 = pd.read_csv("/content/drive/MyDrive/빅예분3조/Data/prescale/KPU_DATA34.csv", encoding='euc-kr')
df3 = pd.read_csv("/content/drive/MyDrive/빅예분3조/Data/prescale/KPU_DATA19.csv", encoding='euc-kr')

In [ ]:
df2.rename(columns = lambda x: "SCHOOL_" + x, inplace = True)
df3.rename(columns = lambda x: "CHILD_" + x, inplace = True)

In [ ]:
del df1['Unnamed: 0']
del df2['SCHOOL_Unnamed: 0']
del df3['CHILD_Unnamed: 0']

In [ ]:
df2.rename(columns = {'SCHOOL_ACPT_YM':'ACPT_YM','SCHOOL_PLCST_NM':'PLCST_NM'},inplace=True)

In [ ]:
df3.rename(columns = {'CHILD_STRD_YR':'STRD_YR','CHILD_PLCST_NM':'PLCST_NM'},inplace=True)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8465 entries, 0 to 8464
Data columns (total 48 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ACPT_YM                  8465 non-null   int64
 1   PLCST_NM                 8465 non-null   object
 2   RPRT_CASCNT_WHOL         8465 non-null   int64
 3   RPRT_SEX_MALE            8465 non-null   int64
 4   RPRT_SEX_FMLE            8465 non-null   int64
 5   RPRT_SEX_UNKWN           8465 non-null   int64
 6   RPRT_SEX_ETC             8465 non-null   int64
 7   ACPT_EMERG_TYPE_EMERG    8465 non-null   int64
 8   ACPT_EMERG_TYPE_IMPRTNC  8465 non-null   int64
 9   ACPT_EMERG_TYPE_GNRL     8465 non-null   int64
 10  ACPT_EMERG_TYPE_CVAPP    8465 non-null   int64
 11  ACPT_EMERG_TYPE_ETC      8465 non-null   int64
 12  OCRN_DOTW_SNDD           8465 non-null   int64
 13  OCRN_DOTW_MON            8465 non-null   int64
 14  OCRN_DOTW_TUE            8465 non-null   int64
 15  OCRN_DOTW_WED            8465 non-null   int64
 16  OCRN_DOTW_THU            8465 non-null   int64
 17  OCRN_DOTW_FRI            8465 non-null   int64
 18  OCRN_DOTW_SAT            8465 non-null   int64
 19  OCRN_TIZN_00             8465 non-null   int64
 20  OCRN_TIZN_01             8465 non-null   int64
 21  OCRN_TIZN_02             8465 non-null   int64
 22  OCRN_TIZN_03             8465 non-null   int64
 23  OCRN_TIZN_04             8465 non-null   int64
 24  OCRN_TIZN_05             8465 non-null   int64
 25  OCRN_TIZN_06             8465 non-null   int64
 26  OCRN_TIZN_07             8465 non-null   int64
 27  OCRN_TIZN_08             8465 non-null   int64
 28  OCRN_TIZN_09             8465 non-null   int64
 29  OCRN_TIZN_10             8465 non-null   int64
 30  OCRN_TIZN_11             8465 non-null   int64
 31  OCRN_TIZN_12             8465 non-null   int64
 32  OCRN_TIZN_13             8465 non-null   int64
 33  OCRN_TIZN_14             8465 non-null   int64
 34  OCRN_TIZN_15             8465 non-null   int64
 35  OCRN_TIZN_16             8465 non-null   int64
 36  OCRN_TIZN_17             8465 non-null   int64
 37  OCRN_TIZN_18             8465 non-null   int64
 38  OCRN_TIZN_19             8465 non-null   int64
 39  OCRN_TIZN_20             8465 non-null   int64
 40  OCRN_TIZN_21             8465 non-null   int64
 41  OCRN_TIZN_22             8465 non-null   int64
 42  OCRN_TIZN_23             8465 non-null   int64
 43  ADDR                     8465 non-null   object
 44  SI                       8465 non-null   object
 45  SGG                      8459 non-null   object
 46  LON                      8416 non-null   float64
 47  LAT                      8416 non-null   float64
dtypes: float64(2), int64(42), object(4)
memory usage: 3.1+ MB

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5579 entries, 0 to 5578
Data columns (total 43 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ACPT_YM                         5579 non-null   int64
 1   PLCST_NM                        5579 non-null   object
 2   SCHOOL_RPRT_CASCNT_WHOL         5579 non-null   int64
 3   SCHOOL_RPRT_SEX_MALE            5579 non-null   int64
 4   SCHOOL_RPRT_SEX_FMLE            5579 non-null   int64
 5   SCHOOL_RPRT_SEX_UNKWN           5579 non-null   int64
 6   SCHOOL_RPRT_SEX_ETC             5579 non-null   int64
 7   SCHOOL_ACPT_EMERG_TYPE_EMERG    5579 non-null   int64
 8   SCHOOL_ACPT_EMERG_TYPE_IMPRTNC  5579 non-null   int64
 9   SCHOOL_ACPT_EMERG_TYPE_GNRL     5579 non-null   int64
 10  SCHOOL_ACPT_EMERG_TYPE_CVAPP    5579 non-null   int64
 11  SCHOOL_ACPT_EMERG_TYPE_ETC      5579 non-null   int64
 12  SCHOOL_OCRN_DOTW_SNDD           5579 non-null   int64
 13  SCHOOL_OCRN_DOTW_MON            5579 non-null   int64
 14  SCHOOL_OCRN_DOTW_TUE            5579 non-null   int64
 15  SCHOOL_OCRN_DOTW_WED            5579 non-null   int64
 16  SCHOOL_OCRN_DOTW_THU            5579 non-null   int64
 17  SCHOOL_OCRN_DOTW_FRI            5579 non-null   int64
 18  SCHOOL_OCRN_DOTW_SAT            5579 non-null   int64
 19  SCHOOL_OCRN_TIZN_00             5579 non-null   int64
 20  SCHOOL_OCRN_TIZN_01             5579 non-null   int64
 21  SCHOOL_OCRN_TIZN_02             5579 non-null   int64
 22  SCHOOL_OCRN_TIZN_03             5579 non-null   int64
 23  SCHOOL_OCRN_TIZN_04             5579 non-null   int64
 24  SCHOOL_OCRN_TIZN_05             5579 non-null   int64
 25  SCHOOL_OCRN_TIZN_06             5579 non-null   int64
 26  SCHOOL_OCRN_TIZN_07             5579 non-null   int64
 27  SCHOOL_OCRN_TIZN_08             5579 non-null   int64
 28  SCHOOL_OCRN_TIZN_09             5579 non-null   int64
 29  SCHOOL_OCRN_TIZN_10             5579 non-null   int64
 30  SCHOOL_OCRN_TIZN_11             5579 non-null   int64
 31  SCHOOL_OCRN_TIZN_12             5579 non-null   int64
 32  SCHOOL_OCRN_TIZN_13             5579 non-null   int64
 33  SCHOOL_OCRN_TIZN_14             5579 non-null   int64
 34  SCHOOL_OCRN_TIZN_15             5579 non-null   int64
 35  SCHOOL_OCRN_TIZN_16             5579 non-null   int64
 36  SCHOOL_OCRN_TIZN_17             5579 non-null   int64
 37  SCHOOL_OCRN_TIZN_18             5579 non-null   int64
 38  SCHOOL_OCRN_TIZN_19             5579 non-null   int64
 39  SCHOOL_OCRN_TIZN_20             5579 non-null   int64
 40  SCHOOL_OCRN_TIZN_21             5579 non-null   int64
 41  SCHOOL_OCRN_TIZN_22             5579 non-null   int64
 42  SCHOOL_OCRN_TIZN_23             5579 non-null   int64
dtypes: int64(42), object(1)
memory usage: 1.8+ MB

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 828 entries, 0 to 827
Data columns (total 46 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   STRD_YR                        828 non-null    int64
 1   PLCST_NM                       828 non-null    object
 2   CHILD_RPRT_CASCNT_WHOL         828 non-null    int64
 3   CHILD_RPRT_SEX_MALE            828 non-null    int64
 4   CHILD_RPRT_SEX_FMLE            828 non-null    int64
 5   CHILD_RPRT_SEX_UNKWN           828 non-null    int64
 6   CHILD_RPRT_SEX_ETC             828 non-null    int64
 7   CHILD_ACPT_EMERG_TYPE_EMERG    828 non-null    int64
 8   CHILD_ACPT_EMERG_TYPE_IMPRTNC  828 non-null    int64
 9   CHILD_ACPT_EMERG_TYPE_GNRL     828 non-null    int64
 10  CHILD_ACPT_EMERG_TYPE_CVAPP    828 non-null    int64
 11  CHILD_ACPT_EMERG_TYPE_ETC      828 non-null    int64
 12  CHILD_DSTVC_RPRT_CNT           828 non-null    int64
 13  CHILD_CHLAB_ASMP               828 non-null    int64
 14  CHILD_CHLAB_ETC                828 non-null    int64
 15  CHILD_OCRN_DOTW_SNDD           828 non-null    int64
 16  CHILD_OCRN_DOTW_MON            828 non-null    int64
 17  CHILD_OCRN_DOTW_TUE            828 non-null    int64
 18  CHILD_OCRN_DOTW_WED            828 non-null    int64
 19  CHILD_OCRN_DOTW_THU            828 non-null    int64
 20  CHILD_OCRN_DOTW_FRI            828 non-null    int64
 21  CHILD_OCRN_DOTW_SAT            828 non-null    int64
 22  CHILD_OCRN_TIZN_00             828 non-null    int64
 23  CHILD_OCRN_TIZN_01             828 non-null    int64
 24  CHILD_OCRN_TIZN_02             828 non-null    int64
 25  CHILD_OCRN_TIZN_03             828 non-null    int64
 26  CHILD_OCRN_TIZN_04             828 non-null    int64
 27  CHILD_OCRN_TIZN_05             828 non-null    int64
 28  CHILD_OCRN_TIZN_06             828 non-null    int64
 29  CHILD_OCRN_TIZN_07             828 non-null    int64
 30  CHILD_OCRN_TIZN_08             828 non-null    int64
 31  CHILD_OCRN_TIZN_09             828 non-null    int64
 32  CHILD_OCRN_TIZN_10             828 non-null    int64
 33  CHILD_OCRN_TIZN_11             828 non-null    int64
 34  CHILD_OCRN_TIZN_12             828 non-null    int64
 35  CHILD_OCRN_TIZN_13             828 non-null    int64
 36  CHILD_OCRN_TIZN_14             828 non-null    int64
 37  CHILD_OCRN_TIZN_15             828 non-null    int64
 38  CHILD_OCRN_TIZN_16             828 non-null    int64
 39  CHILD_OCRN_TIZN_17             828 non-null    int64
 40  CHILD_OCRN_TIZN_18             828 non-null    int64
 41  CHILD_OCRN_TIZN_19             828 non-null    int64
 42  CHILD_OCRN_TIZN_20             828 non-null    int64
 43  CHILD_OCRN_TIZN_21             828 non-null    int64
 44  CHILD_OCRN_TIZN_22             828 non-null    int64
 45  CHILD_OCRN_TIZN_23             828 non-null    int64
dtypes: int64(45), object(1)
memory usage: 297.7+ KB

In [ ]:
df_temp1 = pd.merge(left=df1,right=df2, how='left',on=['ACPT_YM','PLCST_NM'])

In [ ]:
df_temp1.to_csv('/content/drive/MyDrive/빅예분3조/Data/prescale/KPU_DATA_MERGE2.csv')

In [ ]:
len(df_temp1.columns)

89

In [ ]:
df_temp1 = df_temp1.astype({'ACPT_YM':'str'})

In [ ]:
df_temp1['STRD_YR'] = df_temp1['ACPT_YM'].str.slice(0,4)

In [ ]:
df_temp1['STRD_YR']

0       2019
1       2019
2       2019
3       2019
4       2019
        ...
8462    2021
8463    2021
8464    2021
8465    2021
8466    2021
Name: STRD_YR, Length: 8467, dtype: object

In [ ]:
df3 = df3.astype({'STRD_YR':'str'})

In [ ]:
df_temp2 = pd.merge(left=df_temp1,right=df3, how='left',on=['STRD_YR','PLCST_NM'])

In [ ]:
df_temp2.columns

Index(['ACPT_YM', 'PLCST_NM', 'RPRT_CASCNT_WHOL', 'RPRT_SEX_MALE',
       'RPRT_SEX_FMLE', 'RPRT_SEX_UNKWN', 'RPRT_SEX_ETC',
       'ACPT_EMERG_TYPE_EMERG', 'ACPT_EMERG_TYPE_IMPRTNC',
       'ACPT_EMERG_TYPE_GNRL',
       ...
       'CHILD_OCRN_TIZN_14', 'CHILD_OCRN_TIZN_15', 'CHILD_OCRN_TIZN_16',
       'CHILD_OCRN_TIZN_17', 'CHILD_OCRN_TIZN_18', 'CHILD_OCRN_TIZN_19',
       'CHILD_OCRN_TIZN_20', 'CHILD_OCRN_TIZN_21', 'CHILD_OCRN_TIZN_22',
       'CHILD_OCRN_TIZN_23'],
      dtype='object', length=134)

In [ ]:
df_temp2.to_csv("/content/drive/MyDrive/빅예분3조/Data/prescale/KPU_DATA_MERGE3.csv", encoding='euc-kr')